### ISSUE TITLE
Release v1.5.1，无法在Win10 zotero 6.0.26上使用

### ISSUE THREAD

**Issue by Ouyang-y** [qnscholar/zotero-if#1]
Release v1.5.1，无法在Win10 zotero 6.0.26上使用。

无法安装插件“%S”。它可能无法与该版本的 Zotero 兼容。

**Comment by qnscholar** [comment]
Release v1.5.1 仅适用于 Zotero 7，release 页面有说明哦。Zotero 6 请安装  v1.5.0 版。

**Comment by Ouyang-y** [comment]
感谢
