### ISSUE TITLE
更新元数据后知网元数据坏掉了

### ISSUE THREAD

**Issue by Darkluna999** [qnscholar/zotero-if#11]
经过测试，在同时选择多条（其中同时包括无doi的知网条目及有doi的条目）时
工具-更新元数据操作后，无doi的条目被继承**上条目**信息覆盖
测试视频如下
https://user-images.githubusercontent.com/53258301/156934847-b4c8d4fd-2781-408e-b96f-f1cbe2ffcb44.mp4

**Comment by qnscholar** [comment]
> 经过测试，在同时选择多条（其中同时包括无doi的知网条目及有doi的条目）时
> 工具-更新元数据操作后，无doi的条目被继承**上条目**信息覆盖
> 测试视频如下
> https://user-images.githubusercontent.com/53258301/156934847-b4c8d4fd-2781-408e-b96f-f1cbe2ffcb44.mp4

更新元数据针对英文文献。

**Comment by Darkluna999** [comment]
。。。。所以覆盖合理？

**Comment by qnscholar** [comment]
> 。。。。所以覆盖合理？

对英文文献来说，自然是合理的。

**Comment by Darkluna999** [comment]
？继承覆盖合理？对英文文献来说，匹配不到数据也不应该是继承覆盖吧

**Comment by Darkluna999** [comment]
时候不早了，我觉得这是个恶性bug当然你要是觉得合理，当作优化找时间做了吧
