### ISSUE TITLE
期刊名字中有双空格导致不匹配

### ISSUE THREAD

**Issue by pencilheart** [qnscholar/zotero-if#3]
代码中有很多期刊名字之间为两空格导致不能匹配，希望检查更正一下
![Snipaste_2021-12-31_11-56-21](https://user-images.githubusercontent.com/61617063/147802415-33b973bc-1aa1-44a0-a753-3f6d3d943163.png)

**Comment by qnscholar** [comment]
> 代码中有很多期刊名字之间为两空格导致不能匹配，希望检查更正一下
> ![Snipaste_2021-12-31_11-56-21](https://user-images.githubusercontent.com/61617063/147802415-33b973bc-1aa1-44a0-a753-3f6d3d943163.png)

收到，我看下。

**Comment by qnscholar** [comment]
> 代码中有很多期刊名字之间为两空格导致不能匹配，希望检查更正一下
> ![Snipaste_2021-12-31_11-56-21](https://user-images.githubusercontent.com/61617063/147802415-33b973bc-1aa1-44a0-a753-3f6d3d943163.png)

已检查IF库，未发现包含双空格的。也不应当会有双空格。你这张图的搜索方式是不对的的。

**Comment by Lunar-W** [comment]
大神，我也发现这个问题了，就是期刊名字有的比较长，就是中间会有两个空格。
![image](https://user-images.githubusercontent.com/46470041/147907679-3bf2c8d2-b91c-4dd1-b3f8-f7c6a0c71a22.png)

**Comment by Lunar-W** [comment]
手动替换了所有双空格变单个空格，几乎所有的期刊都显示了影响因子了，总之谢谢大神啦。

**Comment by qnscholar** [comment]
收到

**Comment by qnscholar** [comment]
> 大神，我也发现这个问题了，就是期刊名字有的比较长，就是中间会有两个空格。
> ![image](https://user-images.githubusercontent.com/46470041/147907679-3bf2c8d2-b91c-4dd1-b3f8-f7c6a0c71a22.png)

我重新检查了下，我插件中调用的数据是旧版的，那版确实有一些双空格没处理。下一版优化。

**Comment by qnscholar** [comment]
> > 大神，我也发现这个问题了，就是期刊名字有的比较长，就是中间会有两个空格。
> > ![image](https://user-images.githubusercontent.com/46470041/147907679-3bf2c8d2-b91c-4dd1-b3f8-f7c6a0c71a22.png)
> 
> 我重新检查了下，我插件中调用的数据是旧版的，那版确实有一些双空格没处理。下一版优化。

刚刚已发布新版本`v0.0.4`，修复了该问题。

**Comment by qnscholar** [comment]
刚刚发布了新版v0.0.4。修复了该问题。谢谢反馈。
