### ISSUE TITLE
插件有时会变成 Zotero Tag

### ISSUE THREAD

**Issue by lywly** [qnscholar/zotero-if#4]
不知道是不是个例，今天打开Zotero发现`Zotero-IF`没有了，变成了`Zotero Tag`，卸载之后重装又好了。
版本`v0.03`

**Comment by qnscholar** [comment]
> 不知道是不是个例，今天打开Zotero发现`Zotero-IF`没有了，变成了`Zotero Tag`，卸载之后重装又好了。
> 版本`v0.03`

有一行代码要改掉。下一个版本修复。

**Comment by qnscholar** [comment]
> 不知道是不是个例，今天打开Zotero发现`Zotero-IF`没有了，变成了`Zotero Tag`，卸载之后重装又好了。
> 版本`v0.03`

刚刚已发布新版本`v0.0.4`
