### ISSUE TITLE
一点探讨

### ISSUE THREAD

**Issue by lywly** [qnscholar/zotero-if#5]
解压XPI文件看了下，猜测应该是从[期刊查询与选择系统](https://ijournal.topeditsci.com/home)爬下来的数据。
我觉得以这种本地查询的方式匹配IF是很高效的办法，一年更新一次数据库就行了。但目前选择的`期刊名`字段存在写法不规范的问题，是否可以考虑匹配`ISSN`字段？这个字段的写法可能比较统一。

**Comment by qnscholar** [comment]
大部分Zotero文献的ISSN字段是空缺的或写法不规范的，所有还会回到源头问题。因为匹配ISSN的前提是知道对应的正确期刊名是啥。

故，还是会（也只能）基于匹配期刊名。

欢迎探讨，新年快乐。

发自我的iPhone

**Comment by qnscholar** [comment]
> 解压XPI文件看了下，猜测应该是从[期刊查询与选择系统](https://ijournal.topeditsci.com/home)爬下来的数据。
> 我觉得以这种本地查询的方式匹配IF是很高效的办法，一年更新一次数据库就行了。但目前选择的`期刊名`字段存在写法不规范的问题，是否可以考虑匹配`ISSN`字段？这个可能字段的写法可能比较统一。

大部分Zotero文献的ISSN字段是空缺的或写法不规范的，所有还会回到源头问题。因为匹配ISSN的前提是知道对应的正确期刊名是啥。

故，还是会（也只能）基于匹配期刊名。而且会通过收集数据，继续优化匹配。

欢迎探讨，新年快乐。

**Comment by lywly** [comment]
ok，你说的有道理，ISSN可以缺失，但是期刊名一定会有。
目前我也有一些期刊名想要提交，但是觉得发邮件不方便。希望后续能有个在线表格，或者像思维导图的东西，可以直接把不规范的别名提交到规范名称的后面
